### ISSUE TITLE
Move to use nUnit (rather than xUnit)

### ISSUE THREAD

**Issue by darcythomas** [Haacked/Scientist.net#22]
I fear I am opening a can of worms | starting a religious war...

I prefer nUnit over xUnit because:

 - Resharper has better support for running code coverage inside Visual Studio (rather than using the command line) (This is a bug that will be fixed in VS2015.2 apparently)
 - The syntax reads nicer (to me) 
  - e.g.,: `Assert.That(() => Int32.Parse("abc"), Throws.Exception.TypeOf<FormatException>());`

This is a nice to have (for me...) issue.
So totally cool if it is closed etc

**Comment by braydie** [comment]
@darcythomas have you ever used [Fluent Assertions](http://www.fluentassertions.com/)? I find that it offers even more readable tests - I like to avoid using `Assert` in my tests and instead use fluent assertions to have something like `Actual.Should().Be(Expected);`

**Comment by dotnetchris** [comment]
@braydie https://github.com/shouldly/shouldly is way better, especially in regards to the very high quality messages it produces during assertion failures. (It's possible they're equivalent, i haven't used the other in a long time, i've used Shoudly on pretty much every single project in the past 2-3 years+)

**Comment by dotnetchris** [comment]
@darcythomas probably no correct option all, even if you consider nUnit then it falls into whether to use 2.x or 3.x of nUnit. The newer version of nUnit experiences many similar issues that xUnit currently has.

I feel like in terms of testing in .NET there's been alot of 1 step forward and 3 steps to the left.

**Comment by braydie** [comment]
@dotnetchris I haven't come across Shouldly, but it looks very similar - especially down to the assertion messages! Must be a commonality between these sorts of libraries which is nice! 

@darcythomas definitely worth looking at using a library like this instead of just straight up Asserts for readability

**Comment by Haacked** [comment]
Yes, this is a religious argument. :stuck_out_tongue: I don't like that assert syntax because I find it to be too verbose. Sometimes, all that extra "English" makes things less readable rather than more readable once you're used to a terse syntax. I find the approach I've taken with xUnit to be very scannable for me.

Now, this is purely a personal preference and not a universal truth. So I appreciate that others like `NUnit` and `Should` style extension methods and whatnot. So I'm not judging you.

(_But secretly I am_). :stuck_out_tongue:

Also, I appreciate you opening the discussion and that everyone kept it civil. :smile:
