### ISSUE TITLE
Properties vs Methods in interfaces

### ISSUE THREAD

**Issue by M-Zuber** [Haacked/Scientist.net#23]
While browsing the code, one of the first things that will be come across is [this file](https://github.com/Haacked/Scientist.net/blob/master/src/Scientist/IExperiment.cs).

Personally I was very confused at the beginning as to how it all works. I did find that the implementation is [here](https://github.com/Haacked/Scientist.net/blob/master/src/Scientist/Internals/ExperimentBuilder.cs), but it is not clear if methods like [`public void Use(Func<Task<T>> control) { _control = control; }`](https://github.com/Haacked/Scientist.net/blob/master/src/Scientist/Internals/ExperimentBuilder.cs#L17) would ever do more then just set the field.

If it is true that they will only be setting/getting the method to be scienced, then I would like to propose changing the interfaces to declare properties and not methods.

**Comment by joncloud** [comment]
In its current implementation using the methods offers the ability to pass a `Func<T>` into the method, and re-write the delegate so that it gets converted into `Func<Task<T>>`.  With a property, only one or the other would be allowed to be defined.

Also in the [Ruby][] framework the `try` member allows callers to submit a couple of different pieces:
* Through multiple calls different delegates can be submitted in order to track multiple experiments.
* The delegates can be named.

[Ruby]: https://github.com/github/scientist/blob/master/lib/scientist/experiment.rb#L262

I have #14 being evaluated to better align the .NET framework to the Ruby framework, which begins to implement these features.

**Comment by M-Zuber** [comment]
Thank you for the explanation. 
Maybe I'll have to write up some documentation and put this in.
